-- 人形human、动物animal、建筑building、物体object
return {
	{name = 'plastic0_1', type = 'floor', stype = 'plastic'},
	{name = 'plastic1_1', type = 'floor', stype = 'plastic'},
	{name = 'plastic2_1', type = 'floor', stype = 'plastic'},
	{name = 'plastic3_1', type = 'floor', stype = 'plastic'},
	{name = 'lego_griffin', type = 'floor', stype = 'plastic'},
	-- {name = 'wood1', type = 'floor', stype = 'wood'},
	-- {name = 'wood2', type = 'floor', stype = 'wood'},
	-- {name = 'marble1', type = 'floor', stype = 'marble'},
	-- {name = 'marble2', type = 'floor', stype = 'marble'},
	-- {name = 'marble3', type = 'floor', stype = 'marble'},
	-- {name = 'brick1', type = 'floor', stype = 'marble'},
	-- {name = 'brick2', type = 'floor', stype = 'marble'},
	--神秘礼物
	{name = 'Mystery_Reward', type = 'object', stype = 'furniture', mode = 'template', title = "Portrait of Blocki", achievements = {'unlock_Mystery_Reward_Gift'}},
	------------------------------------------------------
	{name = 'lego_f1', type = 'object', stype = 'vehicle', mode = 'template', title = "F1", achievements = {'unlock_lego_f1'}, tags = {'$Modern'}},
	{name = 'lego_car', type = 'object', stype = 'vehicle', mode = 'template', title = "Car", achievements = {'unlock_lego_car'}, tags = {'$Modern'}},
	{name = 'lego_Decorations8', type = 'object', stype = 'vehicle', mode = 'template', title = "Decorations", achievements = {'unlock_lego_Decorations8'}, tags = {'$Cartoon'}},
	{name = 'lego_Decorations9', type = 'object', stype = 'vehicle', mode = 'template', title = "Decorations", achievements = {'unlock_lego_Decorations9'}, tags = {'$Cartoon'}},
	{name = 'lego_Decorations11', type = 'object', stype = 'vehicle', mode = 'template', title = "Decorations", achievements = {'unlock_lego_Decorations11'}, tags = {'$Cartoon'}},
	--human
	{name = 'lego_Dracula', type = 'object', stype = 'human', mode = 'template', title = "Dracula", achievements = {'unlock_lego_Dracula'}, tags = {'$Square Head'}},
	{name = 'lego_SantaElf', type = 'object', stype = 'human', mode = 'template', title = "Santa Elf", achievements = {'unlock_lego_SantaElf'}, tags = {'$Square Head'}},
	{name = 'lego_DemoGorgon', type = 'object', stype = 'human', mode = 'template', title = "Demo Gorgon", achievements = {'unlock_lego_DemoGorgon'}, tags = {'$Square Head'}},
	{name = 'lego_GrimReaper', type = 'object', stype = 'human', mode = 'template', title = "Grim Reaper", achievements = {'unlock_lego_GrimReaper'}, tags = {'$Square Head'}},
	{name = 'lego_MyBrickhead', type = 'object', stype = 'human', mode = 'template', title = "My Brickhead", achievements = {'unlock_lego_MyBrickhead'}, tags = {'$Square Head'}},
	{name = 'lego_RomanEmperor', type = 'object', stype = 'human', mode = 'template', title = "Roman Emperor", achievements = {'unlock_lego_RomanEmperor'}, tags = {'$Square Head'}},
	{name = 'lego_TeddyRoosevelt', type = 'object', stype = 'human', mode = 'template', title = "Teddy Roosevelt", achievements = {'unlock_lego_TeddyRoosevelt'}, tags = {'$Square Head'}},
	{name = 'lego_baseless_knight', type = 'object', stype = 'human', mode = 'template', title = "Baseless Knight", achievements = {'unlock_lego_baseless_knight'}, tags = {'$Square Head'}},
	{name = 'lego_LondonPoliceBrickheadz', type = 'object', stype = 'human', mode = 'template', title = "London Police Brickheadz", achievements = {'unlock_lego_LondonPoliceBrickheadz'}, tags = {'$Square Head'}},
	--animal
	{name = 'lego_rhino', type = 'object', stype = 'animal', mode = 'template', title = "Rhino", achievements = {'unlock_lego_rhino'}, tags = {'$Zoo'}},
	{name = 'lego_gorilla', type = 'object', stype = 'animal', mode = 'template', title = "Gorilla", achievements = {'unlock_lego_gorilla'}, tags = {'$Zoo'}},
	{name = 'lego_Elephant', type = 'object', stype = 'animal', mode = 'template', title = "Elephant", achievements = {'unlock_lego_Elephant'}, tags = {'$Zoo'}},
	{name = 'lego_griffin', type = 'object', stype = 'animal', mode = 'template', title = "Griffin", achievements = {'unlock_lego_griffin'}, tags = {'$Museum'}},
	{name = 'lego_Bird', type = 'object', stype = 'animal', mode = 'template', title = "Bird", achievements = {'unlock_lego_Bird'}, tags = {'$Zoo'}},
	{name = 'lego_Whale', type = 'object', stype = 'animal', mode = 'template', title = "Whale", achievements = {'unlock_lego_Whale'}, tags = {'$Zoo'}},
	{name = 'lego_RubberDucky', type = 'object', stype = 'animal', mode = 'template', title = "Rubber Ducky", achievements = {'unlock_lego_RubberDucky'}, tags = {'$Warm'}},
	{name = 'lego_T-RexFossil', type = 'object', stype = 'animal', mode = 'template', title = "T-Rex Fossil", achievements = {'unlock_lego_T-RexFossil'}, tags = {'$Museum'}},
	{name = 'lego_Penguin', type = 'object', stype = 'animal', mode = 'template', title = "Penguin", achievements = {'unlock_lego_Penguin'}, tags = {'$Zoo'}},
	{name = 'lego_gorilla2', type = 'object', stype = 'animal', mode = 'template', title = "Gorilla2", achievements = {'unlock_lego_gorilla2'}, tags = {'$Zoo'}},
	{name = 'lego_DragonHead', type = 'object', stype = 'animal', mode = 'template', title = "Dragon Head", achievements = {'unlock_lego_DragonHead'}, tags = {'$Museum'}},
	{name = 'lego_FossilSmilodon', type = 'object', stype = 'animal', mode = 'template', title = "Fossil Smilodon", achievements = {'unlock_lego_FossilSmilodon'}, tags = {'$Museum'}},
	{name = 'lego_Panda', type = 'object', stype = 'animal', mode = 'template', title = "New Panda Bear overhaul", achievements = {'unlock_lego_Panda'}, tags = {'$Zoo'}},
	{name = 'lego_PteranodonFossil', type = 'object', stype = 'animal', mode = 'template', title = "Pteranodon Fossil", achievements = {'unlock_lego_PteranodonFossil'}, tags = {'$Museum'}},
	{name = 'lego_IAMWILDCATBrickheadz', type = 'object', stype = 'animal', mode = 'template', title = "Iamwildcat Brickheadz", achievements = {'unlock_lego_IAMWILDCATBrickheadz'}, tags = {'$Warm'}},
	--natural
	{name = 'Natural_Plant1', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant1'}},
	{name = 'Natural_Plant2', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant2'}},
	{name = 'Natural_Plant3', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant3'}},
	{name = 'Natural_Plant4', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant4'}},
	{name = 'Natural_Plant5', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant5'}},
	{name = 'Natural_Plant6', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant6'}},
	{name = 'Natural_Plant7', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant7'}},
	{name = 'Natural_Plant8', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant8'}},
	{name = 'Natural_Plant9', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant9'}},
	{name = 'Natural_Plant10', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant10'}},
	{name = 'Natural_Plant11', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'unlock_Natural_Plant11'}},
	{name = 'lego_MoreMeat', type = 'object', stype = 'natural', mode = 'template', title = "More Meat", achievements = {'unlock_lego_MoreMeat'}},
	{name = 'lego_Sunflower', type = 'object', stype = 'natural', mode = 'template', title = "Sun flower", achievements = {'unlock_lego_Sunflower'}},
	{name = 'White_Plant1', type = 'object', stype = 'natural', mode = 'template', title = "Plant", achievements = {'WhitePlant1_object'}},
	{name = 'Frosty_Tree', type = 'object', stype = 'natural', mode = 'template', title = "Tree", achievements = {'unlock_Frosty_Tree'}, tags = {'$Frosty'}},
	-- {name = 'lego_Decorations19', type = 'object', stype = 'natural', mode = 'template', title = "Decorations19", achievements = {'unlock_lego_Decorations19'}, tags = {'$Natural'}},
	-- {name = 'lego_Decorations20', type = 'object', stype = 'natural', mode = 'template', title = "Decorations20", achievements = {'unlock_lego_Decorations20'}, tags = {'$Natural'}},
	--furniture
	{name = 'White_SingleBed1', type = 'object', stype = 'furniture', mode = 'template', title = "Single Bed", achievements = {'unlock_White_SingleBed1'}, tags = {'$Fashion'}},
	{name = 'White_SingleBed2', type = 'object', stype = 'furniture', mode = 'template', title = "Single Bed", achievements = {'unlock_White_SingleBed2'}, tags = {'$Fashion'}},
	{name = 'White_Sofa1', type = 'object', stype = 'furniture', mode = 'template', title = "Brown Sofa", achievements = {'unlock_White_Sofa1'}, tags = {'$Fashion'}},
	{name = 'White_Sofa2', type = 'object', stype = 'furniture', mode = 'template', title = "White Sofa", achievements = {'unlock_White_Sofa2'}, tags = {'$Fashion'}},
	{name = 'White_Sofa3', type = 'object', stype = 'furniture', mode = 'template', title = "White Sofa", achievements = {'unlock_White_Sofa3'}, tags = {'$Fashion'}},
	{name = 'White_Sofa4', type = 'object', stype = 'furniture', mode = 'template', title = "White Sofa", achievements = {'unlock_White_Sofa4'}, tags = {'$Fashion'}},
	{name = 'White_Sofa5', type = 'object', stype = 'furniture', mode = 'template', title = "White Sofa", achievements = {'unlock_White_Sofa5'}, tags = {'$Fashion'}},
	{name = 'White_TeaTable', type = 'object', stype = 'furniture', mode = 'template', title = "White Tea Table", achievements = {'unlock_White_TeaTable'}, tags = {'$Fashion'}},
	{name = 'White_TeaTable2', type = 'object', stype = 'furniture', mode = 'template', title = "Black Tea Table", achievements = {'unlock_White_TeaTable2'}, tags = {'$Fashion'}},
	{name = 'White_Chair1', type = 'object', stype = 'furniture', mode = 'template', title = "Black Chair", achievements = {'unlock_White_Chair1'}, tags = {'$Fashion'}},
	{name = 'White_Chair2', type = 'object', stype = 'furniture', mode = 'template', title = "Chair", achievements = {'unlock_White_Chair2'}, tags = {'$Fashion'}},
	{name = 'White_Chair3', type = 'object', stype = 'furniture', mode = 'template', title = "White Chair", achievements = {'unlock_White_Chair3'}, tags = {'$Fashion'}},
	{name = 'White_Chair4', type = 'object', stype = 'furniture', mode = 'template', title = "White Chair", achievements = {'unlock_White_Chair4'}, tags = {'$Fashion'}},
	{name = 'White_Stairs', type = 'object', stype = 'furniture', mode = 'template', title = "Stairs", achievements = {'unlock_White_Stairs'}, tags = {'$Fashion'}},
	{name = 'White_Carpet', type = 'object', stype = 'furniture', mode = 'template', title = "Carpet", achievements = {'unlock_White_Carpet'}, tags = {'$Fashion'}},
	{name = 'White_Clock', type = 'object', stype = 'furniture', mode = 'template', title = "Clock", achievements = {'unlock_White_Clock'}, tags = {'$Fashion'}},
	{name = 'White_Fireplace', type = 'object', stype = 'furniture', mode = 'template', title = "White Fireplace", achievements = {'unlock_White_Fireplace'}, tags = {'$Fashion'}},
	{name = 'White_Wallhanging', type = 'object', stype = 'furniture', mode = 'template', title = "Wallhanging", achievements = {'unlock_White_Wallhanging'}, tags = {'$Fashion'}},
	{name = 'White_Cupboard1', type = 'object', stype = 'furniture', mode = 'template', title = "Cupboard", achievements = {'unlock_White_Cupboard1'}, tags = {'$Fashion'}},
	{name = 'White_Cupboard2', type = 'object', stype = 'furniture', mode = 'template', title = "Cupboard", achievements = {'unlock_White_Cupboard2'}, tags = {'$Fashion'}},
	{name = 'White_Cupboard3', type = 'object', stype = 'furniture', mode = 'template', title = "Cupboard", achievements = {'unlock_White_Cupboard3'}, tags = {'$Fashion'}},
	{name = 'White_BedsideTable1', type = 'object', stype = 'furniture', mode = 'template', title = "Bedside Table", achievements = {'unlock_White_BedsideTable1'}, tags = {'$Fashion'}},
	{name = 'White_BedsideTable2', type = 'object', stype = 'furniture', mode = 'template', title = "Bedside Table", achievements = {'unlock_White_BedsideTable2'}, tags = {'$Fashion'}},
	{name = 'White_Mural1', type = 'object', stype = 'furniture', mode = 'template', title = "Mural", achievements = {'unlock_White_Mural1'}, tags = {'$Fashion'}},
	{name = 'White_Mural2', type = 'object', stype = 'furniture', mode = 'template', title = "Mural", achievements = {'unlock_White_Mural2'}, tags = {'$Fashion'}},
	{name = 'White_WashBasin', type = 'object', stype = 'furniture', mode = 'template', title = "Washbasin", achievements = {'unlock_White_WashBasin'}, tags = {'$Fashion'}},
	{name = 'White_WashBasin2', type = 'object', stype = 'furniture', mode = 'template', title = "Washbasin", achievements = {'unlock_White_WashBasin2'}, tags = {'$Fashion'}},
	{name = 'White_WashBasin3', type = 'object', stype = 'furniture', mode = 'template', title = "Washbasin", achievements = {'unlock_White_WashBasin3'}, tags = {'$Fashion'}},
	{name = 'White_Toilet', type = 'object', stype = 'furniture', mode = 'template', title = "Toilet", achievements = {'unlock_White_Toilet'}, tags = {'$Fashion'}},
	{name = 'White_Bathtub', type = 'object', stype = 'furniture', mode = 'template', title = "Bathtub", achievements = {'unlock_White_Bathtub'}, tags = {'$Fashion'}},
	{name = 'White_Curtain1', type = 'object', stype = 'furniture', mode = 'template', title = "Curtain", achievements = {'unlock_White_Curtain1'}, tags = {'$Fashion'}},
	{name = 'White_Curtain2', type = 'object', stype = 'furniture', mode = 'template', title = "Curtain", achievements = {'unlock_White_Curtain2'}, tags = {'$Fashion'}},
	-- {name = 'White_Partition', type = 'object', stype = 'furniture', mode = 'template', title = "White Partition", achievements = {'unlock_White_Partition'}, tags = {'$Fashion'}},
	{name = 'Children_A', type = 'object', stype = 'furniture', mode = 'template', title = "A", achievements = {'unlock_Children_A'}, tags = {'$Childish'}},
	{name = 'Children_B', type = 'object', stype = 'furniture', mode = 'template', title = "B", achievements = {'unlock_Children_B'}, tags = {'$Childish'}},
	{name = 'Children_C', type = 'object', stype = 'furniture', mode = 'template', title = "C", achievements = {'unlock_Children_C'}, tags = {'$Childish'}},
	{name = 'Children_D', type = 'object', stype = 'furniture', mode = 'template', title = "D", achievements = {'unlock_Children_D'}, tags = {'$Childish'}},
	{name = 'Children_E', type = 'object', stype = 'furniture', mode = 'template', title = "E", achievements = {'unlock_Children_E'}, tags = {'$Childish'}},
	{name = 'Children_F', type = 'object', stype = 'furniture', mode = 'template', title = "F", achievements = {'unlock_Children_F'}, tags = {'$Childish'}},
	{name = 'Children_BoxBlue', type = 'object', stype = 'furniture', mode = 'template', title = "Blue Box", achievements = {'unlock_Children_BoxBlue'}, tags = {'$Childish'}},
	{name = 'Children_BoxGreen', type = 'object', stype = 'furniture', mode = 'template', title = "Green Box", achievements = {'unlock_Children_BoxGreen'}, tags = {'$Childish'}},
	{name = 'Children_BoxPurple', type = 'object', stype = 'furniture', mode = 'template', title = "Purple Box", achievements = {'unlock_Children_BoxPurple'}, tags = {'$Childish'}},
	{name = 'Children_BoxRed', type = 'object', stype = 'furniture', mode = 'template', title = "Red Box", achievements = {'unlock_Children_BoxRed'}, tags = {'$Childish'}},
	{name = 'Children_BoxYellow', type = 'object', stype = 'furniture', mode = 'template', title = "Yellow Box", achievements = {'unlock_Children_BoxYellow'}, tags = {'$Childish'}},
	{name = 'Children_Castle', type = 'object', stype = 'furniture', mode = 'template', title = "Castle", achievements = {'unlock_Children_Castle'}, tags = {'$Childish'}},
	{name = 'Children_Slide', type = 'object', stype = 'furniture', mode = 'template', title = "Slide", achievements = {'unlock_Children_Slide'}, tags = {'$Childish'}},
	{name = 'Children_Slide2', type = 'object', stype = 'furniture', mode = 'template', title = "Slide", achievements = {'unlock_Children_Slide2'}, tags = {'$Childish'}},
	{name = 'Children_Train', type = 'object', stype = 'furniture', mode = 'template', title = "Train", achievements = {'unlock_Children_Train'}, tags = {'$Childish'}},
	{name = 'Children_FlyingSaucer', type = 'object', stype = 'furniture', mode = 'template', title = "Flying Saucer", achievements = {'unlock_Children_FlyingSaucer'}, tags = {'$Childish'}},
	{name = 'Children_Frog', type = 'object', stype = 'furniture', mode = 'template', title = "Frog", achievements = {'unlock_Children_Frog'}, tags = {'$Childish'}},
	{name = 'Children_Plane', type = 'object', stype = 'furniture', mode = 'template', title = "Plane", achievements = {'unlock_Children_Plane'}, tags = {'$Childish'}},
	{name = 'Children_YellowCar', type = 'object', stype = 'furniture', mode = 'template', title = "Yellow Car", achievements = {'unlock_Children_YellowCar'}, tags = {'$Childish'}},
	{name = 'Children_PoliceCar', type = 'object', stype = 'furniture', mode = 'template', title = "Police Car", achievements = {'unlock_Children_PoliceCar'}, tags = {'$Childish'}},
	{name = 'Children_Carpet', type = 'object', stype = 'furniture', mode = 'template', title = "Carpet", achievements = {'unlock_Children_Carpet'}, tags = {'$Childish'}},
	{name = 'Children_Rocket', type = 'object', stype = 'furniture', mode = 'template', title = "Rocket", achievements = {'unlock_Children_Rocket'}, tags = {'$Childish'}},
	{name = 'Children_Bed', type = 'object', stype = 'furniture', mode = 'template', title = "Bed", achievements = {'unlock_Children_Bed'}, tags = {'$Childish'}},
	{name = 'Children_Tent', type = 'object', stype = 'furniture', mode = 'template', title = "Tent", achievements = {'unlock_Children_Tent'}, tags = {'$Childish'}},
	{name = 'Children_Telescope', type = 'object', stype = 'furniture', mode = 'template', title = "Telescope", achievements = {'unlock_Children_Telescope'}, tags = {'$Childish'}},
	{name = 'Children_Wardrobe', type = 'object', stype = 'furniture', mode = 'template', title = "Wardrobe", achievements = {'unlock_Children_Wardrobe'}, tags = {'$Childish'}},
	{name = 'Children_BedsideTable', type = 'object', stype = 'furniture', mode = 'template', title = "Bedside Table", achievements = {'unlock_Children_BedsideTable'}, tags = {'$Childish'}},
	{name = 'Children_Chair', type = 'object', stype = 'furniture', mode = 'template', title = "Chair", achievements = {'unlock_Children_Chair'}, tags = {'$Childish'}},
	{name = 'Children_Chair2', type = 'object', stype = 'furniture', mode = 'template', title = "Chair", achievements = {'unlock_Children_Chair2'}, tags = {'$Childish'}},
	{name = 'Children_Sofa', type = 'object', stype = 'furniture', mode = 'template', title = "Sofa", achievements = {'unlock_Children_Sofa'}, tags = {'$Childish'}},
	{name = 'Children_Sofa2', type = 'object', stype = 'furniture', mode = 'template', title = "Sofa", achievements = {'unlock_Children_Sofa2'}, tags = {'$Childish'}},
	{name = 'Children_Wardrobe2', type = 'object', stype = 'furniture', mode = 'template', title = "Wardrobe", achievements = {'unlock_Children_Wardrobe2'}, tags = {'$Childish'}},
	{name = 'Children_Table', type = 'object', stype = 'furniture', mode = 'template', title = "Table", achievements = {'unlock_Children_Table'}, tags = {'$Childish'}},
	{name = 'Sweet_Bed', type = 'object', stype = 'furniture', mode = 'template', title = "Bed", achievements = {'unlock_Sweet_Bed'}, tags = {'$Sweet'}},
	{name = 'Sweet_Carpet', type = 'object', stype = 'furniture', mode = 'template', title = "Carpet", achievements = {'unlock_Sweet_Carpet'}, tags = {'$Sweet'}},
	{name = 'Sweet_Carpet2', type = 'object', stype = 'furniture', mode = 'template', title = "Carpet", achievements = {'unlock_Sweet_Carpet2'}, tags = {'$Sweet'}},
	{name = 'Sweet_Carpet3', type = 'object', stype = 'furniture', mode = 'template', title = "Carpet", achievements = {'unlock_Sweet_Carpet3'}, tags = {'$Sweet'}},
	{name = 'Sweet_Chair', type = 'object', stype = 'furniture', mode = 'template', title = "Chair", achievements = {'unlock_Sweet_Chair'}, tags = {'$Sweet'}},
	{name = 'Sweet_Clock', type = 'object', stype = 'furniture', mode = 'template', title = "Clock", achievements = {'unlock_Sweet_Clock'}, tags = {'$Sweet'}},
	{name = 'Sweet_Curtain', type = 'object', stype = 'furniture', mode = 'template', title = "Curtain", achievements = {'unlock_Sweet_Curtain'}, tags = {'$Sweet'}},
	{name = 'Sweet_Duck', type = 'object', stype = 'furniture', mode = 'template', title = "Duck", achievements = {'unlock_Sweet_Duck'}, tags = {'$Sweet'}},
	{name = 'Sweet_Heart', type = 'object', stype = 'furniture', mode = 'template', title = "Carpet", achievements = {'unlock_Sweet_Heart'}, tags = {'$Sweet'}},
	{name = 'Sweet_Heart2', type = 'object', stype = 'furniture', mode = 'template', title = "Carpet", achievements = {'unlock_Sweet_Heart2'}, tags = {'$Sweet'}},
	{name = 'Sweet_Orangutan', type = 'object', stype = 'furniture', mode = 'template', title = "Orangutan", achievements = {'unlock_Sweet_Orangutan'}, tags = {'$Sweet'}},
	{name = 'Sweet_Slippers', type = 'object', stype = 'furniture', mode = 'template', title = "Slippers", achievements = {'unlock_Sweet_Slippers'}, tags = {'$Sweet'}},
	{name = 'Sweet_Sofa', type = 'object', stype = 'furniture', mode = 'template', title = "Sofa", achievements = {'unlock_Sweet_Sofa'}, tags = {'$Sweet'}},
	{name = 'Sweet_Sofa2', type = 'object', stype = 'furniture', mode = 'template', title = "Sofa", achievements = {'unlock_Sweet_Sofa2'}, tags = {'$Sweet'}},
	{name = 'Sweet_Tablelamp', type = 'object', stype = 'furniture', mode = 'template', title = "Table Lamp", achievements = {'unlock_Sweet_Tablelamp'}, tags = {'$Sweet'}},
	{name = 'Sweet_Teatable', type = 'object', stype = 'furniture', mode = 'template', title = "Tea Table", achievements = {'unlock_Sweet_Teatable'}, tags = {'$Sweet'}},
	{name = 'Sweet_Wallhanging', type = 'object', stype = 'furniture', mode = 'template', title = "Wallhanging", achievements = {'unlock_Sweet_Wallhanging'}, tags = {'$Sweet'}},
	{name = 'Sweet_Wallhanging2', type = 'object', stype = 'furniture', mode = 'template', title = "Wallhanging", achievements = {'unlock_Sweet_Wallhanging2'}, tags = {'$Sweet'}},
	{name = 'Sweet_Wallhanging3', type = 'object', stype = 'furniture', mode = 'template', title = "Wallhanging", achievements = {'unlock_Sweet_Wallhanging3'}, tags = {'$Sweet'}},
	{name = 'Sweet_Wardrobe', type = 'object', stype = 'furniture', mode = 'template', title = "Wardrobe", achievements = {'unlock_Sweet_Wardrobe'}, tags = {'$Sweet'}},
	{name = 'Frosty_Penguin', type = 'object', stype = 'furniture', mode = 'template', title = "Penguin", achievements = {'unlock_Frosty_Penguin'}, tags = {'$Frosty'}},
	{name = 'Frosty_Penguin2', type = 'object', stype = 'furniture', mode = 'template', title = "Penguin", achievements = {'unlock_Frosty_Penguin2'}, tags = {'$Frosty'}},
	{name = 'Frosty_Penguin3', type = 'object', stype = 'furniture', mode = 'template', title = "Penguin", achievements = {'unlock_Frosty_Penguin3'}, tags = {'$Frosty'}},
	{name = 'Frosty_Seal', type = 'object', stype = 'furniture', mode = 'template', title = "Seal", achievements = {'unlock_Frosty_Seal'}, tags = {'$Frosty'}},
	{name = 'Frosty_Shark', type = 'object', stype = 'furniture', mode = 'template', title = "Shark", achievements = {'unlock_Frosty_Shark'}, tags = {'$Frosty'}},
	{name = 'Frosty_Snowman', type = 'object', stype = 'furniture', mode = 'template', title = "Snowman", achievements = {'unlock_Frosty_Snowman'}, tags = {'$Frosty'}},
	{name = 'Frosty_Fort', type = 'object', stype = 'furniture', mode = 'template', title = "Fort", achievements = {'unlock_Frosty_Fort'}, tags = {'$Frosty'}},
	{name = 'Frosty_Bear', type = 'object', stype = 'furniture', mode = 'template', title = "Bear", achievements = {'unlock_Frosty_Bear'}, tags = {'$Frosty'}},
	{name = 'Frosty_Bridge', type = 'object', stype = 'furniture', mode = 'template', title = "Bridge", achievements = {'unlock_Frosty_Bridge'}, tags = {'$Frosty'}},
	{name = 'Frosty_Cloud', type = 'object', stype = 'furniture', mode = 'template', title = "Cloud", achievements = {'unlock_Frosty_Cloud'}, tags = {'$Frosty'}},
	{name = 'Frosty_Fire1', type = 'object', stype = 'furniture', mode = 'template', title = "Fire", achievements = {'unlock_Frosty_Fire1'}, tags = {'$Frosty'}},
	{name = 'Frosty_Fire2', type = 'object', stype = 'furniture', mode = 'template', title = "Fire", achievements = {'unlock_Frosty_Fire2'}, tags = {'$Frosty'}},
	{name = 'Frosty_Sun', type = 'object', stype = 'furniture', mode = 'template', title = "Sun", achievements = {'unlock_Frosty_Sun'}, tags = {'$Frosty'}},
	-- space
	{name = 'lego_plane', type = 'object', stype = 'space', mode = 'template', title = "Plane", achievements = {'unlock_lego_plane'}, tags = {'$Science fiction'}},
	{name = 'lego_thousand_falcon', type = 'object', stype = 'space', mode = 'template', title = "Plane", achievements = {'unlock_lego_thousand_falcon'}, tags = {'$Science fiction'}},
	{name = 'lego_Telescope', type = 'object', stype = 'space', mode = 'template', title = "Astronomical telescope", achievements = {'unlock_lego_Telescope'}, tags = {'$Astronomical'}},
	--military
	{name = 'lego_Gatling', type = 'object', stype = 'military', mode = 'template', title = "Gatling", achievements = {'unlock_lego_Gatling'}, tags = {'$Science fiction'}},
	--supplies
	{name = 'lego_piano4', type = 'object', stype = 'supplies', mode = 'template', title = "Piano", achievements = {'unlock_lego_piano4'}, tags = {'$Music'}},
	{name = 'lego_piano3', type = 'object', stype = 'supplies', mode = 'template', title = "Upright Piano", achievements = {'unlock_lego_piano3'}, tags = {'$Music'}},
	{name = 'lego_ARCADE-1', type = 'object', stype = 'supplies', mode = 'template', title = "Simulator1", achievements = {'unlock_lego_ARCADE-1'}, tags = {'$arcade'}},
	{name = 'lego_ARCADE-2', type = 'object', stype = 'supplies', mode = 'template', title = "Simulator2", achievements = {'unlock_lego_ARCADE-2'}, tags = {'$arcade'}},
	{name = 'lego_piano', type = 'object', stype = 'supplies', mode = 'template', title = "Grand Piano Black", achievements = {'unlock_lego_piano'}, tags = {'$Music'}},
	{name = 'lego_piano2', type = 'object', stype = 'supplies', mode = 'template', title = "Grand Piano Blue", achievements = {'unlock_lego_piano2'}, tags = {'$Music'}},
	{name = 'lego_piano5', type = 'object', stype = 'supplies', mode = 'template', title = "Grand Piano White", achievements = {'unlock_lego_piano5'}, tags = {'$Music'}},
	{name = 'lego_Microphone', type = 'object', stype = 'supplies', mode = 'template', title = "Microphone", achievements = {'unlock_lego_Microphone'}, tags = {'$Music'}},
	{name = 'lego_Club-cabinet', type = 'object', stype = 'supplies', mode = 'template', title = "Pool Cue Rack", achievements = {'lego_Club-cabinet'}, tags = {'$arcade'}},
	{name = 'lego_desk-blue', type = 'object', stype = 'supplies', mode = 'template', title = "Billiard Table1", achievements = {'unlock_lego_desk-blue'}, tags = {'$arcade'}},
	{name = 'lego_Gamemachine', type = 'object', stype = 'supplies', mode = 'template', title = "Game Machine", achievements = {'unlock_lego_Gamemachine'}, tags = {'$arcade'}},
	{name = 'lego_desk-green', type = 'object', stype = 'supplies', mode = 'template', title = "Billiard Table2", achievements = {'unlock_lego_desk-green'}, tags = {'$arcade'}},
	{name = 'lego_Camera', type = 'object', stype = 'supplies', mode = 'template', title = "Camera Design by Chris McVeigh", achievements = {'unlock_lego_Camera'}, tags = {'$Modern'}},
	{name = 'lego_vending-machine', type = 'object', stype = 'supplies', mode = 'template', title = "Vending Machine1", achievements = {'unlock_lego_vending-machine'}, tags = {'$arcade'}},
	{name = 'lego_Typewriter', type = 'object', stype = 'supplies', mode = 'template', title = "Typewriter", achievements = {'unlock_lego_Typewriter'}, tags = {'$Restoring ancient ways'}},
	--decoration
	{name = 'lego_light1', type = 'object', stype = 'decoration1', mode = 'template', title = "Light", achievements = {'unlock_lego_light1'}, tags = {'$Restoring ancient ways'}},
	{name = 'lego_light2', type = 'object', stype = 'decoration1', mode = 'template', title = "Light", achievements = {'unlock_lego_light2'}, tags = {'$Restoring ancient ways'}},
	{name = 'lego_light3', type = 'object', stype = 'decoration1', mode = 'template', title = "Light", achievements = {'unlock_lego_light3'}, tags = {'$Restoring ancient ways'}},
	{name = 'lego_Decorations5', type = 'object', stype = 'decoration1', mode = 'template', title = "Decorations", achievements = {'unlock_lego_Decorations5'}, tags = {'$Cartoon'}},
	{name = 'lego_Decorations6', type = 'object', stype = 'decoration1', mode = 'template', title = "Decorations", achievements = {'unlock_lego_Decorations6'}, tags = {'$Cartoon'}},
	{name = 'lego_Decorations10', type = 'object', stype = 'decoration1', mode = 'template', title = "Decorations", achievements = {'unlock_lego_Decorations10'}, tags = {'$Cartoon'}},
	{name = 'lego_Decorations3', type = 'object', stype = 'decoration1', mode = 'template', title = "Decorations", achievements = {'unlock_lego_Decorations3'}, tags = {'$Restoring ancient ways'}},
	{name = 'lego_Decorations23', type = 'object', stype = 'decoration1', mode = 'template', title = "Decorations", achievements = {'unlock_lego_Decorations23'}, tags = {'$Restoring ancient ways'}},
	-- {name = 'lego_vending-machine2', type = 'object', stype = 'object', mode = 'template', title = "Vending Machine2", achievements = {'unlock_lego_vending-machine2'}},
	{name = 'lego_box', type = 'object', stype = 'object', mode = 'template', title = "Travelling Luggage Large", tags = {'$Middle Ages'}, achievements = {'unlock_lego_box'}},
	-- {name = 'lego_mushroom', type = 'object', stype = 'object', mode = 'template', title = "Mushroom"},
	{name = 'gramophone', type = 'object', stype = 'object', mode = 'template', title = "Gramophone", achievements = {'unlock_gramophone'}},
	-- {name = 'lego_AvatarDoor', type = 'object', stype = 'object', mode = 'template', title = "AvatarDoor"},
	-- {name = 'lego_Avatar1', type = 'avatar', stype = 'human', mode = 'template', title = "Avatar1"},
	-- {name = 'lego_Avatar2', type = 'avatar', stype = 'human', mode = 'template', title = "Avatar2"},
	-- {name = 'lego_Avatar3', type = 'avatar', stype = 'human', mode = 'template', title = "Avatar3"},
	{name = 'TV', type = 'object', stype = 'object', mode = 'template', title = "TV", achievements = {'unlock_TV'}},
	{name = 'work', type = 'object', stype = 'object', mode = 'template', title = "Workbench", achievements = {'unlock_work'}},
	-- {name = 'work02', type = 'object', stype = 'object', mode = 'template', title = "Paint Bucket", achievements = {'unlock_work02'}},
	-- {name = 'lego_picture', type = 'object', stype = 'object', mode = 'template', achievements = {'unlock_lego_picture'}},
	-- {name = 'lego_picture2', type = 'object', stype = 'object', mode = 'template', achievements = {'unlock_lego_picture2'}},	
	--demo版：
	{name = 'brickwhite', type = 'object', stype = 'brick'},
	{name = 'brickgrey', type = 'object', stype = 'brick'},
	{name = 'brickyellow', type = 'object', stype = 'brick'},
	{name = 'brickbabyblue', type = 'object', stype = 'brick'},
	{name = 'brickgreen', type = 'object', stype = 'brick'},
	{name = 'brickred', type = 'object', stype = 'brick'},
	{name = 'brickorange', type = 'object', stype = 'brick'},
	{name = 'brickblue', type = 'object', stype = 'brick'},
	{name = 'brickpurple', type = 'object', stype = 'brick'},
	{name = 'tree2', type = 'object', stype = 'tree'},
	{name = 'tree3', type = 'object', stype = 'tree'},
	{name = 'tree4', type = 'object', stype = 'tree'},
	{name = 'bridge', type = 'object', stype = 'other'},
	{name = 'skeleton', type = 'object', stype = 'other'},
	{name = 'chair', type = 'object', stype = 'other'},
	{name = 'desk', type = 'object', stype = 'other'},
	{name = 'Tool_01', type = 'object', stype = 'other'},
	{name = 'Tool_02', type = 'object', stype = 'other'},
	{name = 'Tool_03', type = 'object', stype = 'other'},
	{name = 'Tool_04', type = 'object', stype = 'other'},
	{name = 'house_001', type = 'object', stype = 'other'},
	{name = 'up_direction', type = 'blockui', stype = 'button'},
	{name = 'down_direction', type = 'blockui', stype = 'button'},
	{name = 'left_direction', type = 'blockui', stype = 'button'},
	{name = 'right_direction', type = 'blockui', stype = 'button'},
	{name = 'circlebutton', type = 'blockui', stype = 'button'},
	{name = 'number', type = 'blockui', stype = 'label'},

	-- {name = 'mario_box', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_brick', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_castle', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_flag', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_flagpole', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_floor', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_god', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_flower', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_monster', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_mushroom', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_turtles', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	-- {name = 'mario_turtlesbody', type = 'object', stype = 'decoration', mode = 'template', title = "steps"},
	------------
	-- {name = 'music_steps', type = 'object', stype = 'visible', mode = 'template', title = "music steps", disableEdit = true},
	-- {name = 'music_steps2', type = 'object', stype = 'visible', mode = 'template', title = "music steps", disableEdit = true},
	-- {name = 'neverup_template4', type = 'object', stype = 'decoration1', mode = 'template', title = "steps"},
	-- {name = 'neverup_template1', type = 'object', stype = 'decoration1', mode = 'template', title = "springboard"},
	-- {name = 'neverup_template2', type = 'object', stype = 'decoration1', mode = 'template', title = "spikesboard"},
	-- {name = 'neverup_template3', type = 'object', stype = 'decoration1', mode = 'template', title = "flipboard"},
	-- {name = 'neverup_template5', type = 'object', stype = 'decoration1', mode = 'template', title = "left conveyor belt"},
	-- {name = 'neverup_template6', type = 'object', stype = 'decoration1', mode = 'template', title = "right conveyor belt"},
	-- {name = 'neverup_template7', type = 'object', stype = 'decoration1', mode = 'template', title = "left moving plate"},
	-- {name = 'neverup_template8', type = 'object', stype = 'decoration1', mode = 'template', title = "right moving plate"},
	--PIANO BIG1
	{name = 'piano_bigc1', type = 'object', stype = 'piano', mode = 'template', title = "Piano C1", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigc1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano C1#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigd1', type = 'object', stype = 'piano', mode = 'template', title = "Piano D1", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigd1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano D1#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bige1', type = 'object', stype = 'piano', mode = 'template', title = "Piano E1", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigf1', type = 'object', stype = 'piano', mode = 'template', title = "Piano F1", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigf1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano F1#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigg1', type = 'object', stype = 'piano', mode = 'template', title = "Piano G1", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigg1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano G1#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_biga1', type = 'object', stype = 'piano', mode = 'template', title = "Piano A1", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_biga1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano A1#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigb1', type = 'object', stype = 'piano', mode = 'template', title = "Piano B1", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_bigc', type = 'object', stype = 'piano', mode = 'template', title = "Piano C", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bigch', type = 'object', stype = 'piano', mode = 'template', title = "Piano C#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bigd', type = 'object', stype = 'piano', mode = 'template', title = "Piano D", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bigdh', type = 'object', stype = 'piano', mode = 'template', title = "Piano D#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bige', type = 'object', stype = 'piano', mode = 'template', title = "Piano E", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bigf', type = 'object', stype = 'piano', mode = 'template', title = "Piano F", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bigfh', type = 'object', stype = 'piano', mode = 'template', title = "Piano F#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bigg', type = 'object', stype = 'piano', mode = 'template', title = "Piano G", stype2 = 'piano', disableEdit = true},
	{name = 'piano_biggh', type = 'object', stype = 'piano', mode = 'template', title = "Piano G#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_biga', type = 'object', stype = 'piano', mode = 'template', title = "Piano A", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bigah', type = 'object', stype = 'piano', mode = 'template', title = "Piano A#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_bigb', type = 'object', stype = 'piano', mode = 'template', title = "Piano B", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallc', type = 'object', stype = 'instrument', mode = 'template', title = "Piano c", stype2 = 'piano', disableEdit = true}, -- disableEdit = true
	{name = 'piano_smallch', type = 'object', stype = 'piano', mode = 'template', title = "Piano c#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smalld', type = 'object', stype = 'piano', mode = 'template', title = "Piano d", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smalldh', type = 'object', stype = 'piano', mode = 'template', title = "Piano d#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smalle', type = 'object', stype = 'piano', mode = 'template', title = "Piano e", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallf', type = 'object', stype = 'piano', mode = 'template', title = "Piano f", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallfh', type = 'object', stype = 'piano', mode = 'template', title = "Piano f#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallg', type = 'object', stype = 'piano', mode = 'template', title = "Piano g", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallgh', type = 'object', stype = 'piano', mode = 'template', title = "Piano g#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smalla', type = 'object', stype = 'piano', mode = 'template', title = "Piano a", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallah', type = 'object', stype = 'piano', mode = 'template', title = "Piano a#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallb', type = 'object', stype = 'piano', mode = 'template', title = "Piano b", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallc1', type = 'object', stype = 'piano', mode = 'template', title = "Piano c1", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smallc1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano c1#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smalld1', type = 'object', stype = 'piano', mode = 'template', title = "Piano d1", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smalld1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano d1#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smalle1', type = 'object', stype = 'piano', mode = 'template', title = "Piano e1", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallf1', type = 'object', stype = 'piano', mode = 'template', title = "Piano f1", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallf1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano f1#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallg1', type = 'object', stype = 'piano', mode = 'template', title = "Piano g1", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallg1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano g1#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smalla1', type = 'object', stype = 'piano', mode = 'template', title = "Piano a1", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smalla1h', type = 'object', stype = 'piano', mode = 'template', title = "Piano a1#", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallb1', type = 'object', stype = 'piano', mode = 'template', title = "Piano b1", stype2 = 'piano', disableEdit = true},
	{name = 'piano_smallc2', type = 'object', stype = 'piano', mode = 'template', title = "Piano c2", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smallc2h', type = 'object', stype = 'piano', mode = 'template', title = "Piano c2#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smalld2', type = 'object', stype = 'piano', mode = 'template', title = "Piano d2", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smalld2h', type = 'object', stype = 'piano', mode = 'template', title = "Piano d2#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smalle2', type = 'object', stype = 'piano', mode = 'template', title = "Piano e2", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smallf2', type = 'object', stype = 'piano', mode = 'template', title = "Piano f2", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smallf2h', type = 'object', stype = 'piano', mode = 'template', title = "Piano f2#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smallg2', type = 'object', stype = 'piano', mode = 'template', title = "Piano g2", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smallg2h', type = 'object', stype = 'piano', mode = 'template', title = "Piano g2#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smalla2', type = 'object', stype = 'piano', mode = 'template', title = "Piano a2", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smalla2h', type = 'object', stype = 'piano', mode = 'template', title = "Piano a2#", stype2 = 'piano', disableEdit = true}, 
	{name = 'piano_smallb2', type = 'object', stype = 'piano', mode = 'template', title = "Piano b2", stype2 = 'piano', disableEdit = true}, 	
	--GUITAR
	{name = 'guitar_bigc1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar C1", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigc1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar C1#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigd1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar D1", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigd1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar D1#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bige1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar E1", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigf1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar F1", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigf1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar F1#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigg1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar G1", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigg1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar G1#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_biga1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar A1", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_biga1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar A1#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigb1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar B1", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_bigc', type = 'object', stype = 'guitar', mode = 'template', title = "guitar C", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bigch', type = 'object', stype = 'guitar', mode = 'template', title = "guitar C#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bigd', type = 'object', stype = 'guitar', mode = 'template', title = "guitar D", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bigdh', type = 'object', stype = 'guitar', mode = 'template', title = "guitar D#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bige', type = 'object', stype = 'guitar', mode = 'template', title = "guitar E", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bigf', type = 'object', stype = 'guitar', mode = 'template', title = "guitar F", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bigfh', type = 'object', stype = 'guitar', mode = 'template', title = "guitar F#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bigg', type = 'object', stype = 'guitar', mode = 'template', title = "guitar G", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_biggh', type = 'object', stype = 'guitar', mode = 'template', title = "guitar G#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_biga', type = 'object', stype = 'guitar', mode = 'template', title = "guitar A", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bigah', type = 'object', stype = 'guitar', mode = 'template', title = "guitar A#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_bigb', type = 'object', stype = 'guitar', mode = 'template', title = "guitar B", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallc', type = 'object', stype = 'instrument', mode = 'template', title = "guitar c", stype2 = 'guitar', disableEdit = true}, -- disableEdit = true
	{name = 'guitar_smallch', type = 'object', stype = 'guitar', mode = 'template', title = "guitar c#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smalld', type = 'object', stype = 'guitar', mode = 'template', title = "guitar d", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smalldh', type = 'object', stype = 'guitar', mode = 'template', title = "guitar d#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smalle', type = 'object', stype = 'guitar', mode = 'template', title = "guitar e", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallf', type = 'object', stype = 'guitar', mode = 'template', title = "guitar f", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallfh', type = 'object', stype = 'guitar', mode = 'template', title = "guitar f#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallg', type = 'object', stype = 'guitar', mode = 'template', title = "guitar g", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallgh', type = 'object', stype = 'guitar', mode = 'template', title = "guitar g#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smalla', type = 'object', stype = 'guitar', mode = 'template', title = "guitar a", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallah', type = 'object', stype = 'guitar', mode = 'template', title = "guitar a#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallb', type = 'object', stype = 'guitar', mode = 'template', title = "guitar b", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallc1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar c1", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smallc1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar c1#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smalld1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar d1", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smalld1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar d1#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smalle1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar e1", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallf1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar f1", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallf1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar f1#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallg1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar g1", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallg1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar g1#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smalla1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar a1", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smalla1h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar a1#", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallb1', type = 'object', stype = 'guitar', mode = 'template', title = "guitar b1", stype2 = 'guitar', disableEdit = true},
	{name = 'guitar_smallc2', type = 'object', stype = 'guitar', mode = 'template', title = "guitar c2", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smallc2h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar c2#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smalld2', type = 'object', stype = 'guitar', mode = 'template', title = "guitar d2", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smalld2h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar d2#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smalle2', type = 'object', stype = 'guitar', mode = 'template', title = "guitar e2", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smallf2', type = 'object', stype = 'guitar', mode = 'template', title = "guitar f2", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smallf2h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar f2#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smallg2', type = 'object', stype = 'guitar', mode = 'template', title = "guitar g2", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smallg2h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar g2#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smalla2', type = 'object', stype = 'guitar', mode = 'template', title = "guitar a2", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smalla2h', type = 'object', stype = 'guitar', mode = 'template', title = "guitar a2#", stype2 = 'guitar', disableEdit = true}, 
	{name = 'guitar_smallb2', type = 'object', stype = 'guitar', mode = 'template', title = "guitar b2", stype2 = 'guitar', disableEdit = true}, 
	--HARP
	{name = 'harp_bigc1', type = 'object', stype = 'harp', mode = 'template', title = "harp C1", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigc1h', type = 'object', stype = 'harp', mode = 'template', title = "harp C1#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigd1', type = 'object', stype = 'harp', mode = 'template', title = "harp D1", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigd1h', type = 'object', stype = 'harp', mode = 'template', title = "harp D1#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bige1', type = 'object', stype = 'harp', mode = 'template', title = "harp E1", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigf1', type = 'object', stype = 'harp', mode = 'template', title = "harp F1", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigf1h', type = 'object', stype = 'harp', mode = 'template', title = "harp F1#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigg1', type = 'object', stype = 'harp', mode = 'template', title = "harp G1", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigg1h', type = 'object', stype = 'harp', mode = 'template', title = "harp G1#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_biga1', type = 'object', stype = 'harp', mode = 'template', title = "harp A1", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_biga1h', type = 'object', stype = 'harp', mode = 'template', title = "harp A1#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigb1', type = 'object', stype = 'harp', mode = 'template', title = "harp B1", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_bigc', type = 'object', stype = 'harp', mode = 'template', title = "harp C", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bigch', type = 'object', stype = 'harp', mode = 'template', title = "harp C#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bigd', type = 'object', stype = 'harp', mode = 'template', title = "harp D", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bigdh', type = 'object', stype = 'harp', mode = 'template', title = "harp D#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bige', type = 'object', stype = 'harp', mode = 'template', title = "harp E", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bigf', type = 'object', stype = 'harp', mode = 'template', title = "harp F", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bigfh', type = 'object', stype = 'harp', mode = 'template', title = "harp F#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bigg', type = 'object', stype = 'harp', mode = 'template', title = "harp G", stype2 = 'harp', disableEdit = true},
	{name = 'harp_biggh', type = 'object', stype = 'harp', mode = 'template', title = "harp G#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_biga', type = 'object', stype = 'harp', mode = 'template', title = "harp A", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bigah', type = 'object', stype = 'harp', mode = 'template', title = "harp A#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_bigb', type = 'object', stype = 'harp', mode = 'template', title = "harp B", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallc', type = 'object', stype = 'instrument', mode = 'template', title = "harp c", stype2 = 'harp', disableEdit = true}, -- disableEdit = true
	{name = 'harp_smallch', type = 'object', stype = 'harp', mode = 'template', title = "harp c#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smalld', type = 'object', stype = 'harp', mode = 'template', title = "harp d", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smalldh', type = 'object', stype = 'harp', mode = 'template', title = "harp d#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smalle', type = 'object', stype = 'harp', mode = 'template', title = "harp e", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallf', type = 'object', stype = 'harp', mode = 'template', title = "harp f", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallfh', type = 'object', stype = 'harp', mode = 'template', title = "harp f#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallg', type = 'object', stype = 'harp', mode = 'template', title = "harp g", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallgh', type = 'object', stype = 'harp', mode = 'template', title = "harp g#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smalla', type = 'object', stype = 'harp', mode = 'template', title = "harp a", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallah', type = 'object', stype = 'harp', mode = 'template', title = "harp a#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallb', type = 'object', stype = 'harp', mode = 'template', title = "harp b", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallc1', type = 'object', stype = 'harp', mode = 'template', title = "harp c1", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smallc1h', type = 'object', stype = 'harp', mode = 'template', title = "harp c1#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smalld1', type = 'object', stype = 'harp', mode = 'template', title = "harp d1", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smalld1h', type = 'object', stype = 'harp', mode = 'template', title = "harp d1#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smalle1', type = 'object', stype = 'harp', mode = 'template', title = "harp e1", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallf1', type = 'object', stype = 'harp', mode = 'template', title = "harp f1", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallf1h', type = 'object', stype = 'harp', mode = 'template', title = "harp f1#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallg1', type = 'object', stype = 'harp', mode = 'template', title = "harp g1", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallg1h', type = 'object', stype = 'harp', mode = 'template', title = "harp g1#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smalla1', type = 'object', stype = 'harp', mode = 'template', title = "harp a1", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smalla1h', type = 'object', stype = 'harp', mode = 'template', title = "harp a1#", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallb1', type = 'object', stype = 'harp', mode = 'template', title = "harp b1", stype2 = 'harp', disableEdit = true},
	{name = 'harp_smallc2', type = 'object', stype = 'harp', mode = 'template', title = "harp c2", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smallc2h', type = 'object', stype = 'harp', mode = 'template', title = "harp c2#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smalld2', type = 'object', stype = 'harp', mode = 'template', title = "harp d2", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smalld2h', type = 'object', stype = 'harp', mode = 'template', title = "harp d2#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smalle2', type = 'object', stype = 'harp', mode = 'template', title = "harp e2", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smallf2', type = 'object', stype = 'harp', mode = 'template', title = "harp f2", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smallf2h', type = 'object', stype = 'harp', mode = 'template', title = "harp f2#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smallg2', type = 'object', stype = 'harp', mode = 'template', title = "harp g2", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smallg2h', type = 'object', stype = 'harp', mode = 'template', title = "harp g2#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smalla2', type = 'object', stype = 'harp', mode = 'template', title = "harp a2", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smalla2h', type = 'object', stype = 'harp', mode = 'template', title = "harp a2#", stype2 = 'harp', disableEdit = true}, 
	{name = 'harp_smallb2', type = 'object', stype = 'harp', mode = 'template', title = "harp b2", stype2 = 'harp', disableEdit = true}, 
	--VIOLIN
	{name = 'violin_bigc1', type = 'object', stype = 'violin', mode = 'template', title = "violin C1", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigc1h', type = 'object', stype = 'violin', mode = 'template', title = "violin C1#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigd1', type = 'object', stype = 'violin', mode = 'template', title = "violin D1", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigd1h', type = 'object', stype = 'violin', mode = 'template', title = "violin D1#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bige1', type = 'object', stype = 'violin', mode = 'template', title = "violin E1", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigf1', type = 'object', stype = 'violin', mode = 'template', title = "violin F1", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigf1h', type = 'object', stype = 'violin', mode = 'template', title = "violin F1#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigg1', type = 'object', stype = 'violin', mode = 'template', title = "violin G1", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigg1h', type = 'object', stype = 'violin', mode = 'template', title = "violin G1#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_biga1', type = 'object', stype = 'violin', mode = 'template', title = "violin A1", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_biga1h', type = 'object', stype = 'violin', mode = 'template', title = "violin A1#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigb1', type = 'object', stype = 'violin', mode = 'template', title = "violin B1", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_bigc', type = 'object', stype = 'violin', mode = 'template', title = "violin C", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bigch', type = 'object', stype = 'violin', mode = 'template', title = "violin C#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bigd', type = 'object', stype = 'violin', mode = 'template', title = "violin D", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bigdh', type = 'object', stype = 'violin', mode = 'template', title = "violin D#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bige', type = 'object', stype = 'violin', mode = 'template', title = "violin E", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bigf', type = 'object', stype = 'violin', mode = 'template', title = "violin F", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bigfh', type = 'object', stype = 'violin', mode = 'template', title = "violin F#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bigg', type = 'object', stype = 'violin', mode = 'template', title = "violin G", stype2 = 'violin', disableEdit = true},
	{name = 'violin_biggh', type = 'object', stype = 'violin', mode = 'template', title = "violin G#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_biga', type = 'object', stype = 'violin', mode = 'template', title = "violin A", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bigah', type = 'object', stype = 'violin', mode = 'template', title = "violin A#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_bigb', type = 'object', stype = 'violin', mode = 'template', title = "violin B", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallc', type = 'object', stype = 'instrument', mode = 'template', title = "violin c", stype2 = 'violin', disableEdit = true}, -- disableEdit = true
	{name = 'violin_smallch', type = 'object', stype = 'violin', mode = 'template', title = "violin c#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smalld', type = 'object', stype = 'violin', mode = 'template', title = "violin d", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smalldh', type = 'object', stype = 'violin', mode = 'template', title = "violin d#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smalle', type = 'object', stype = 'violin', mode = 'template', title = "violin e", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallf', type = 'object', stype = 'violin', mode = 'template', title = "violin f", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallfh', type = 'object', stype = 'violin', mode = 'template', title = "violin f#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallg', type = 'object', stype = 'violin', mode = 'template', title = "violin g", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallgh', type = 'object', stype = 'violin', mode = 'template', title = "violin g#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smalla', type = 'object', stype = 'violin', mode = 'template', title = "violin a", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallah', type = 'object', stype = 'violin', mode = 'template', title = "violin a#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallb', type = 'object', stype = 'violin', mode = 'template', title = "violin b", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallc1', type = 'object', stype = 'violin', mode = 'template', title = "violin c1", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smallc1h', type = 'object', stype = 'violin', mode = 'template', title = "violin c1#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smalld1', type = 'object', stype = 'violin', mode = 'template', title = "violin d1", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smalld1h', type = 'object', stype = 'violin', mode = 'template', title = "violin d1#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smalle1', type = 'object', stype = 'violin', mode = 'template', title = "violin e1", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallf1', type = 'object', stype = 'violin', mode = 'template', title = "violin f1", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallf1h', type = 'object', stype = 'violin', mode = 'template', title = "violin f1#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallg1', type = 'object', stype = 'violin', mode = 'template', title = "violin g1", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallg1h', type = 'object', stype = 'violin', mode = 'template', title = "violin g1#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smalla1', type = 'object', stype = 'violin', mode = 'template', title = "violin a1", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smalla1h', type = 'object', stype = 'violin', mode = 'template', title = "violin a1#", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallb1', type = 'object', stype = 'violin', mode = 'template', title = "violin b1", stype2 = 'violin', disableEdit = true},
	{name = 'violin_smallc2', type = 'object', stype = 'violin', mode = 'template', title = "violin c2", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smallc2h', type = 'object', stype = 'violin', mode = 'template', title = "violin c2#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smalld2', type = 'object', stype = 'violin', mode = 'template', title = "violin d2", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smalld2h', type = 'object', stype = 'violin', mode = 'template', title = "violin d2#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smalle2', type = 'object', stype = 'violin', mode = 'template', title = "violin e2", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smallf2', type = 'object', stype = 'violin', mode = 'template', title = "violin f2", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smallf2h', type = 'object', stype = 'violin', mode = 'template', title = "violin f2#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smallg2', type = 'object', stype = 'violin', mode = 'template', title = "violin g2", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smallg2h', type = 'object', stype = 'violin', mode = 'template', title = "violin g2#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smalla2', type = 'object', stype = 'violin', mode = 'template', title = "violin a2", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smalla2h', type = 'object', stype = 'violin', mode = 'template', title = "violin a2#", stype2 = 'violin', disableEdit = true}, 
	{name = 'violin_smallb2', type = 'object', stype = 'violin', mode = 'template', title = "violin b2", stype2 = 'violin', disableEdit = true}, 
	--BARRIER
	{name = 'barrier_hurdles1', type = 'object', stype = 'barrier', mode = 'template', title = "Roadblock 1"},
	{name = 'barrier_hurdles2', type = 'object', stype = 'barrier', mode = 'template', title = "Roadblock 2"},
	{name = 'barrier_updoor', type = 'object', stype = 'barrier', mode = 'template', title = "Up & Down Wall 1"},
	{name = 'barrier_downdoor', type = 'object', stype = 'barrier', mode = 'template', title = "Up & Down Wall 2"},
	{name = 'barrier_door', type = 'object', stype = 'barrier', mode = 'template', title = "Revolving Door 1A"},
	{name = 'barrier_door2', type = 'object', stype = 'barrier', mode = 'template', title = "Revolving Door 1B"},
	{name = 'barrier_door2A', type = 'object', stype = 'barrier', mode = 'template', title = "Revolving Door 2A"},
	{name = 'barrier_door2B', type = 'object', stype = 'barrier', mode = 'template', title = "Revolving Door 2B"},
	{name = 'barrier_door3A', type = 'object', stype = 'barrier', mode = 'template', title = "Revolving Door 3A"},
	{name = 'barrier_door3B', type = 'object', stype = 'barrier', mode = 'template', title = "Revolving Door 3B"},
	{name = 'barrier_Autodoor', type = 'object', stype = 'barrier', mode = 'template', title = "Automatic Door"},
	{name = 'barrier_Pendulum', type = 'object', stype = 'barrier', mode = 'template', title = "Pendulum 1"},
	{name = 'barrier_skateboard', type = 'object', stype = 'barrier', mode = 'template', title = "Skate Board"},
	-- {name = 'barrier_downband', type = 'object', stype = 'barrier', mode = 'template', title = "Slow down Belt"},
	-- {name = 'barrier_upband', type = 'object', stype = 'barrier', mode = 'template', title = "Speed up Belt"},
	-- {name = 'barrier_gloves', type = 'object', stype = 'barrier', mode = 'template', title = "Boxing glove"},
	-- {name = 'barrier_spikes', type = 'object', stype = 'barrier', mode = 'template', title = "Spike Trap"},
	--decoration
	{name = 'Fireworks1', type = 'object', stype = 'decoration', mode = 'template', title = "Fireworks 1"},
	{name = 'Fireworks2', type = 'object', stype = 'decoration', mode = 'template', title = "Fireworks 2"},
	{name = 'Fireworks3', type = 'object', stype = 'decoration', mode = 'template', title = "Fireworks 3"},
	{name = 'decoration_Bomberman', type = 'object', stype = 'decoration', mode = 'template', title = "Bomberman"},
	{name = 'decoration_Cup', type = 'object', stype = 'decoration', mode = 'template', title = "Cup"},
	{name = 'decoration_duck', type = 'object', stype = 'decoration', mode = 'template', title = "Space Duck"},
	{name = 'decoration_flower1', type = 'object', stype = 'decoration', mode = 'template', title = "Flower 1"},
	{name = 'decoration_flower2', type = 'object', stype = 'decoration', mode = 'template', title = "Flower 2"},
	{name = 'decoration_penguin', type = 'object', stype = 'decoration', mode = 'template', title = "Penguin"},
	{name = 'decoration_plant', type = 'object', stype = 'decoration', mode = 'template', title = "Plant"},
	{name = 'decoration_seal', type = 'object', stype = 'decoration', mode = 'template', title = "Seal"},
	{name = 'decoration_Skeleton', type = 'object', stype = 'decoration', mode = 'template', title = "Skeleton"},
	{name = 'decoration_snowman', type = 'object', stype = 'decoration', mode = 'template', title = "Snowman"},
	{name = 'decoration_Treants', type = 'object', stype = 'decoration', mode = 'template', title = "Treants"},
	-- {name = 'template_beard', type = 'avatar', mode = 'template', canswitch = true, title = "beard"},
	{name = 'defaultavatar2', type = 'avatar', mode = 'template', canswitch = true, title = "Droid", template_icon = 'bardtemplate_icon1.png'},
	{name = 'dummybox', type = 'object', stype = 'functions', mode = 'template', title = "Dummy Box"},
	{name = 'copybox', type = 'object', stype = 'functions', mode = 'template', title = "Copy Box"},
	{name = 'location_enter', type = 'object', stype = 'functions', mode = 'template', title = "Start Point"},
	{name = 'location_exit', type = 'object', stype = 'functions', mode = 'template', title = "Goal Point"},
	{name = 'xfx_obj', type = 'object', stype = 'functions', mode = 'template', title = "Effect"},
	{name = 'newcamera', type = 'object', stype = 'functions', mode = 'template', title = "Camera"},
	{name = 'locationnew', type = 'object', stype = 'functions', mode = 'template', title = "Marker"},
	{name = 'marker_train', type = 'object', stype = 'functions', mode = 'template', title = "Train"},
	{name = 'marker_shapeProbe', type = 'object', stype = 'functions', mode = 'template', title = "ShapeProbe"},
	{name = 'template_boringape', type = 'avatar', mode = 'template', title = "boringape", achievements = {'talk42'}},
}